### ISSUE TITLE
Pre-release

### ISSUE THREAD

**Issue by dimqua** [csmarosi/wifiAutOff#1]
Please provide an apk for testing the app.

**Comment by Poussinou** [comment]
@csmarosi 

Can you please tag your releases (see [here](https://help.github.com/articles/creating-releases/)), it would be helpful for the F-Droid release (request [here](https://gitlab.com/fdroid/rfp/issues/120)). You could also attach the binaries to your releases (see [here](https://blog.github.com/2013-07-02-release-your-software/)) as asked by dimqua.

That's pretty easy and very helpful for those of us who aren't using Google services.

**Comment by IzzySoft** [comment]
Uh, and could you please make your versionName matching the release name (i.e. omitting the commit hash)? Thanks!

**Comment by csmarosi** [comment]
I've updated the versionName along with some fixes. (Sorry for the long delay).

**Comment by IzzySoft** [comment]
Thanks, @csmarosi – that looks good now! I've updated the Metadata in the RFP and set it to "ready for build" – further I updated it in my repo (should show up soon™).
